name: Helm

on: 
  push: 
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Helm lint & package & push
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u eumelnet --password-stdin
          helm lint .
          helm package .
          helm push $(ls *.tgz| head -1) oci://ghcr.io/${{ github.repository_owner }}/charts

